services:

  db:
    image: postgres:16
    container_name: tasks-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: tasks-web
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_files:/app/staticfiles

  nginx:
    image: nginx:alpine
    container_name: tasks-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/app/staticfiles:ro
    depends_on:
      - web



volumes:
  postgres_data:
  static_files:
