# Generated by Django 5.2.15 on 2026-06-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_date_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-created_at']},
        ),
    ]
